const namespace = 'search-destinations';

export const SEARCH_DESTINATION = `${namespace}/SEARCH_DESTINATION`;
export const SEARCH_DESTINATIONS_BY_QUERY = `${namespace}/SEARCH_DESTINATIONS_BY_QUERY`;
export const SEARCH_DESTINATIONS_BY_COORDINATES = `${namespace}/SEARCH_DESTINATIONS_BY_COORDINATES`;
export const SET_DESTINATIONS_BY_COORDS_IDS = `${namespace}/SET_DESTINATIONS_BY_COORDS_IDS`;
export const SET_DESTINATIONS_BY_QUERY_IDS = `${namespace}/SET_DESTINATIONS_BY_QUERY_IDS`;
export const SET_DESTINATIONS_FROM_MAP_BOX_IDS = `${namespace}/SET_DESTINATIONS_FROM_MAP_BOX_IDS`;
export const CLEAR_DESTINATIONS_BY_QUERY_IDS = `${namespace}/CLEAR_DESTINATIONS_BY_QUERY_IDS`;
export const SET_SEARCH_DESTINATION_DATES = `${namespace}/SET_SEARCH_DESTINATION_DATES`;
export const SET_SEARCH_DESTINATION_LOCATION = `${namespace}/SET_SEARCH_DESTINATION_LOCATION`;
export const SET_SEARCH_DESTINATION_LOCATION_INTENT = `${namespace}/SET_SEARCH_DESTINATION_LOCATION_INTENT`;
export const SET_SEARCH_DESTINATION_ALL_LOCATIONS = `${namespace}/SET_SEARCH_DESTINATION_ALL_LOCATIONS`;
export const CLEAR_SEARCH_DESTINATION_PARAMS = `${namespace}/CLEAR_SEARCH_DESTINATION_PARAMS`;
export const SET_ACTIVE_CAMPER_ID = `${namespace}/SET_ACTIVE_CAMPER_ID`;
export const FETCH_SEARCH_RESULT_DATA = `${namespace}/FETCH_SEARCH_RESULT_DATA`;
// Filters
export const SET_FILTER_VALUE = `${namespace}/SET_FILTER_VALUE`;
export const SET_FILTER_BATCH_VALUE = `${namespace}/SET_FILTER_BATCH_VALUE`;
export const CLEAR_ALL_FILTERS = `${namespace}/CLEAR_ALL_FILTERS`;
export const TOGGLE_MOBILE_FILTERS_VISIBILITY = `${namespace}/TOGGLE_MOBILE_FILTERS_VISIBILITY`;
export const TOGGLE_DESKTOP_MAP_VISIBILITY = `${namespace}/TOGGLE_DESKTOP_MAP_VISIBILITY`;
// Near you destinations
export const FETCH_NEAR_YOU_DESTINATIONS = `${namespace}/FETCH_NEAR_YOU_DESTINATIONS`;
export const SET_NEAR_YOU_DESTINATIONS_IDS = `${namespace}/SET_NEAR_YOU_DESTINATIONS_IDS`;
