version: '3.1'
volumes:
  static:

services:
  server_app:
    build:
      context: .
      args:
        api_host: https://staging-api.vancation.com
        node_env: staging
    volumes:
      - static:/app/static
    expose:
      - 4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/login"]

  web_server:
    build: ./deploy/configs/nginx
    ports:
      - 80:8080
    depends_on:
      - server_app
    volumes:
      - static:/app/static
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
