# Stage: Builder
FROM node:14-alpine as builder

ARG NEXT_PUBLIC_API_HOST
ENV NEXT_PUBLIC_API_HOST $NEXT_PUBLIC_API_HOST

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

ARG NEXT_PUBLIC_FACEBOOK_KEY
ENV NEXT_PUBLIC_FACEBOOK_KEY $NEXT_PUBLIC_FACEBOOK_KEY

ARG NEXT_PUBLIC_GOOGLE_KEY
ENV NEXT_PUBLIC_GOOGLE_KEY $NEXT_PUBLIC_GOOGLE_KEY

ARG NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_SUPPORT_EMAIL $NEXT_PUBLIC_SUPPORT_EMAIL

ARG NEXT_PUBLIC_SUPPORT_PHONE
ENV NEXT_PUBLIC_SUPPORT_PHONE $NEXT_PUBLIC_SUPPORT_PHONE

ARG NEXT_PUBLIC_APP_PHONE
ENV NEXT_PUBLIC_APP_PHONE $NEXT_PUBLIC_APP_PHONE

ARG NEXT_PUBLIC_ACCESS_TOKEN_MAPBOX
ENV NEXT_PUBLIC_ACCESS_TOKEN_MAPBOX $NEXT_PUBLIC_ACCESS_TOKEN_MAPBOX

RUN apk add --update --no-cache python2 git make openssh-client g++

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --production

COPY . .

RUN yarn build

# Stage: Final
FROM node:14-alpine

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

RUN apk add --update --no-cache curl

WORKDIR /app

RUN yarn global add pm2

USER node
COPY --from=builder --chown=node:node /app ./
