const namespace = 'booking';

export const CREATE_CAMPER_BOOKING_INQUIRY = `${namespace}/CREATE_CAMPER_BOOKING_INQUIRY`;
export const SET_CHAT_SECTION_VISIBILITY = `${namespace}/SET_CHAT_SECTION_VISIBILITY`;
export const SET_DETAILS_SECTION_VISIBILITY = `${namespace}/SET_DETAILS_SECTION_VISIBILITY`;
export const FETCH_CAMPER_INQUIRIES = `${namespace}/FETCH_CAMPER_INQUIRIES`;
export const SET_CAMPER_INQUIRIES_IDS = `${namespace}/SET_CAMPER_INQUIRIES_IDS`;
export const SET_CAMPER_INQUIRIES_PAGE = `${namespace}/SET_CAMPER_INQUIRIES_PAGE`;
export const SET_CAMPER_INQUIRIES_TOTAL = `${namespace}/SET_CAMPER_INQUIRIES_TOTAL`;
export const FETCH_CAMPER_BOOKING_INQUIRY = `${namespace}/FETCH_CAMPER_BOOKING_INQUIRY`;
export const SET_FILTERS_VISIBILITY = `${namespace}/SET_FILTERS_VISIBILITY`;
export const SET_ACTIVE_BOOKING_ID = `${namespace}/SET_ACTIVE_BOOKING_ID`;
export const FETCH_BOOKING_CHAT_MESSAGES = `${namespace}/FETCH_BOOKING_CHAT_MESSAGES`;
export const SET_BOOKING_CHAT_MESSAGES_IDS = `${namespace}/SET_BOOKING_CHAT_MESSAGES_IDS`;
export const SET_BOOKING_CHAT_MESSAGES_PAGE = `${namespace}/SET_BOOKING_CHAT_MESSAGES_PAGE`;
export const SET_BOOKING_CHAT_MESSAGES_TOTAL = `${namespace}/SET_BOOKING_CHAT_MESSAGES_TOTAL`;
